export const styles = {
  flex_outer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  flex_container: {
    width: '75rem',
    marginTop: '3rem',
    boxShadow: '0px 25px 55px rgba(209, 208, 219, 0.4)',
    flexDirection: 'column',
  },
  flex_inner_container: {
    margin: '1rem',
    flexDirection: 'column',
    backgroundColor: '#E5F6FF',
    borderRadius: '6px',
    width: '80%',
    padding: '0rem 3rem',
    paddingBottom: '5rem',
  },
  title: {
    height: '5rem',
    alignItems: 'center',
    paddingLeft: '2rem',
    backgroundColor: '#1799DE',
    color: '#fff',
    fontWeight: '600',
    fontFamily: 'Poppins',
    fontSize: '26px',
  },
  flex_column: { flexDirection: 'column', justifyContent: 'center', alignItems: 'center' },
  flex_sub_title: { flexDirection: 'row', marginBottom: '1rem', marginTop: '1rem' },
  sub_title_text: {
    fontFamily: 'Noto Sans',
    fontWeight: '600',
    fontSize: '16px',
    color: '#DF4886',
  },
  filter_icon: {
    color: '#1799DE',
    width: '1.5rem',
    height: '1.5rem',
    marginLeft: 'auto',
    marginRight: '2rem',
  },
  flex_swap_details: { gap: '1rem', alignItems: 'center', marginBottom: '1rem' },
  swap_token_image: { width: '50px', height: '50px' },
  swap_token_select: {
    borderRadius: '10rem',
    outline: 'none',
    border: 0,
    height: '50px',
    paddingInlineEnd: '24px',
    flex: 1,
    width: '6rem',
    fontSize: '22px',
    fontWeight: '600',
    color: '#0A3F5C',
    marginBottom: '2px',
    appearance: 'none',
    WebkitAppearance: 'none',
    marginTop: '5px',
    paddingLeft: '10px',
  },
  swap_token_input: {
    borderRadius: '30px',
    width: '15rem',
    boxShadow: 'none',
    border: 'none',
    outline: 0,
    paddingLeft: '1rem',
    color: '#0A3F5C',
    backgroundColor: '#fff',
    fontSize: '30px',
    fontWeight: '700',
    textAlign: 'right',
    paddingRight: '1.5rem',
  },
  flex_arrow_container: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#DF4886',
    padding: '0.3rem',
    borderRadius: '50px',
  },
  arrow_icon: { width: '2rem', height: '2rem', color: '#fff' },
  hpie_token_image: { width: '60px', height: '50px' },
  flex_slippage_tolerance: { marginLeft: '55%', alignItems: 'center', gap: '0.5rem' },
  slippage_tolerance_text: { color: '#8E8DA0', fontWeight: '600', fontSize: '16px', fontFamily: 'Noto Sans' },
  slippage_tolerance_input: {
    borderRadius: '30px',
    width: '5rem',
    boxShadow: 'none',
    border: 'none',
    outline: 0,
    paddingLeft: '1rem',
    color: '#EFA906',
    backgroundColor: '#fff',
    fontSize: '16px',
    fontWeight: '700',
    textAlign: 'center',
    paddingRight: '1.5rem',
  },
  swap_button: {
    margin: '1rem',
    marginBottom: '4rem',
    cursor: 'pointer',
    backgroundColor: '#1799DE',
    color: '#fff',
    fontSize: '16px',
    fontWeight: '600',
    height: '4rem',
    width: '50%',
    borderRadius: '30px',
    letterSpacing: '0.2rem',
  },
}
