export const styles = {
  flex_outer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  flex_container: {
    width: '75rem',
    marginBottom: '2rem',
    borderRadius: '50px',
    boxShadow: '0px 25px 55px rgba(209, 208, 219, 0.4)',
    flexDirection: 'column',
    background: 'url(/images/lottery-background.png)',
    backgroundPosition: 'center bottom',
    backgroundSize: 'cover',
  },
  flex_inner_container: {
    margin: '1rem',
    flexDirection: 'column',
    backgroundColor: '#E5F6FF',
    borderRadius: '6px',
    width: '80%',
    padding: '0rem 3rem',
    paddingBottom: '5rem',
  },
  title: {
    height: '5rem',
    alignItems: 'center',
    paddingLeft: '2rem',
    backgroundColor: '#1799DE',
    color: '#fff',
    fontWeight: '600',
    fontFamily: 'Poppins',
    fontSize: '26px',
  },
  flex_start_container: { alignItems: 'flex-start', justifyContent: 'flex-start', padding: '40px', gap: '30px' },
  flex_start_inner_container: { width: '50rem', flexDirection: 'column', gap: '2rem' },
  flex_nft_name_container: { flexDirection: 'column', gap: '0.5rem' },
  flex_column: { flexDirection: 'column' },
  series_name_text: { color: '#DF4886', fontSize: '20px', fontWeight: '600' },
  nft_name_text: { color: '#16103A', fontWeight: '700', fontSize: '30px' },
  flex_badges_row: { flexDirection: 'row', gap: '15px' },
  flex_badge_container: {
    border: '2px solid #D8D8D8',
    borderRadius: '30px',
    padding: '0 10px 0 10px',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '0.2rem',
  },
  badge_title_text: { color: '#8E8DA0', fontWeight: '600' },
  badge_value_text: { color: '#0A3F5C' },
  flex_strategy_container: {
    flexDirection: 'column',
    border: '1px solid rgba(142, 141, 160, 0.42)',
    borderRadius: '10px',
    padding: '20px',
    gap: '20px',
  },
  strategy_title_text: { fontWeight: '700', fontSize: '24px' },
  flex_strategy_inner_container: { gap: '15px', flexWrap: 'wrap', width: '40rem' },
  flex_strategy_details_container: {
    backgroundColor: '#E5F6FF',
    borderRadius: '8px',
    width: '200px',
    height: '100px',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '10px',
    padding: '2px',
  },
  strategy_detail_image: { width: '50px', height: '50px' },
  flex_strategy_detail_column: { flexDirection: 'column', gap: '5px' },
  strategy_detail_quantity_text: { fontWeight: '700', fontSize: '22px', color: '#0A3F5C' },
  strategy_detail_value_text: { color: '#8E8DA0', fontSize: '14px', fontWeight: '500' },
  strategy_detail_apy_text: { color: '#0A3F5C', fontFamily: 'Noto Sans', fontWeight: '600', fontSize: '16px' },
  flex_right_container: { flexDirection: 'column', width: '30rem', gap: '1rem' },
  flex_owner_details_container: {
    flexDirection: 'row',
    gap: '10px',
    alignItems: 'center',
    marginLeft: 'auto',
  },
  owner_name_text: { fontSize: '20px', fontWeight: '700', color: '#ABABAB' },
  owner_image: { width: '80px', height: '80px' },

  // Buttons Container
  flex_button_container: { flexDirection: 'row', gap: '2rem', marginTop: '1rem' },
  stake_button: {
    width: '300px',
    height: '50px',
    borderRadius: '40px',
    padding: '0px 20px',
    lineHeight: '48px',
    fontSize: '16px',
    fontWeight: '600',
    backgroundColor: '#1799DE',
    color: '#fff',
    cursor: 'pointer',
    ':hover': {
      border: '2px solid rgb(157 83 182)',
      color: 'rgb(157 83 182)',
    },
    letterSpacing: '3px',
  },
  view_contents_button: {
    width: '300px',
    height: '50px',
    borderRadius: '40px',
    padding: '0px 20px',
    lineHeight: '48px',
    fontSize: '16px',
    fontWeight: '600',
    backgroundColor: '#fff',
    color: '#1799DE',
    cursor: 'pointer',
    border: '2px solid #1799DE',
    ':hover': {
      border: '2px solid rgb(157 83 182)',
      color: 'rgb(157 83 182)',
      backgroundColor: '#fff',
    },
  },
  flex_stake_details: {
    border: '2px solid #EFA906',
    borderRadius: '8px',
    flexDirection: 'column',
    backgroundColor: '#FFFBF4',
    padding: '20px',
    marginTop: '112px',
  },
  stake_details_title: { fontWeight: '700', fontSize: '20px' },
  stake_details_value: { fontWeight: '700', fontSize: '30px', color: '#EFA906' },
  stake_details_comment: { color: '#8E8DA0', fontSize: '16px' },

  // Time Remaining Styles
  time_remaining_container: {
    flexDirection: 'column',
    gap: '30px',
    alignItems: 'center',
    justifyContent: 'center',
  },
  time_remaining_text_container: { gap: '1rem' },
  time_remaining_time_display_text: {
    fontFamily: 'Noto Sans',
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: '30px',
    lineHeight: '150%',
    textAlign: 'center',
    color: '#DF4886',
  },
  time_remaining_comment_text: {
    fontFamily: 'Noto Sans',
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: '30px',
    lineHeight: '150%',
    textAlign: 'center',
    color: '#8E8DA0',
  },
  time_remaining_outer_container: {
    justifyContent: 'center',
    alignItems: 'center',
  },
}
