export const styles = {
  button_input_container: {
    position: 'relative',
    width: '100%',
    overflow: 'hidden',
    marginBottom: '10px',
    backgroundColor: '#fff',
    borderRadius: '31px',
  },
  button_input_max_btn: {
    width: 'min-content',
    height: 'min-content',
    alignSelf: 'center',
    backgroundColor: 'rgba(160, 160, 160, 0.32)',
    borderRadius: '4px',
    fontSize: '12px',
    color: '#8E8DA0',
    fontWeight: '300',
    cursor: 'pointer',
    ':hover': {
      backgroundColor: '#fff',
      border: '2px solid rgba(160, 160, 160, 0.32)',
    },
    padding: '4px',
  },
  button_input_input: {
    position: 'relative',
    height: '56px',
    borderRadius: '30px',
    minWidth: '100%',
    boxShadow: 'none',
    border: 'none',
    outline: 0,
    fontSize: '16px',
    paddingRight: '1rem',
    textAlign: 'right',
    fontWeight: '600',
    color: '#8E8DA0',
  },
  button_input_flex_container: { position: 'absolute', marginTop: 0, height: '100%', gap: '6px', zIndex: '1' },
  info_container: {
    position: 'relative',
    width: '100%',
    overflow: 'hidden',
    marginBottom: '10px',
    backgroundColor: '#fff',
    borderRadius: '31px',
    height: '56px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '0px 27px',
  },
  info_label: {
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: '16px',
    lineHeight: '28px',
    color: '#16103A',
  },
  info_value: {
    fontFamily: 'Noto Sans',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: '16px',
    lineHeight: '28px',
    color: '#8E8DA0',
  },
  select_container: {
    position: 'relative',
    width: '100%',
    height: '60px',
    overflow: 'hidden',
    marginBottom: '10px',
    backgroundColor: '#fff',
    borderRadius: '31px',
  },
  select_label: {
    position: 'absolute',
    marginTop: 6,
    width: '2rem',
    padding: '0px 20px',
    lineHeight: '48px',
    fontSize: '18px',
    top: -4,
    fontWeight: '700',
    color: '#16103A',
    opacity: '0.8',
  },
  select_select: {
    borderRadius: '10rem',
    outline: 'none',
    border: 0,
    minHeight: '3rem',
    textAlign: 'right',
    paddingInlineEnd: '24px',
    marginInline: '5px',
    flex: 1,
    width: '24rem',
    fontSize: '16px',
    fontWeight: '600',
    color: '#8E8DA0',
    marginBottom: '2px',
    appearance: 'none',
    WebkitAppearance: 'none',
    marginTop: '2px',
  },
  switch_container: {
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: '1rem',
    marginLeft: '3rem',
  },
  switch_deposit_text: {
    fontSize: '18px',
    fontWeight: '700',
    color: '#16103A',
    opacity: '0.8',
  },
  switch_inner_container: { padding: '0rem 2rem 0rem 2rem' },
  switch_withdraw_text: {
    fontSize: '18px',
    fontWeight: '700',
    color: '#16103A',
    opacity: '0.8',
  },
}
