export const styles = {
  vault_container: {
    backgroundColor: '#E5F6FF',
    borderRadius: 12,
    maxWidth: 556,
    margin: '0 auto',
  },
  vault_form_tab: {
    width: '50%',
    borderRadius: 12,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all .2s',
    userSelect: 'none',
  },
  vault_action_button: {
    height: 62,
    borderRadius: 62,
    cursor: 'pointer',
    width: '100%',
    flexShrink: 0,
  },
  vault_action_button_container_mobile: {
    display: 'block',
    marginBottom: 2,
    width: '100%',
    [`@media screen and (min-width: 600px)`]: {
      display: 'none',
    },
  },
  vault_action_max_button: {
    width: 44,
    height: 26,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(160, 160, 160, 0.32)',
    borderRadius: '4px',
    color: '#8E8DA0',
    flexShrink: 0,
    margin: '0 8px 0 32px',
    [`@media screen and (min-width: 600px)`]: {
      margin: '0 8px',
    },
  },
  vault_action_input: {
    boxShadow: 'none',
    border: 'none',
    outline: 0,
    textAlign: 'right',
    fontSize: 24,
    fontWeight: 700,
    color: '#8E8DA0',
    paddingRight: 32,
  },
  vault_action_container_desktop: {
    height: 62,
    backgroundColor: '#fff',
    borderRadius: 62,
    overflow: 'hidden',
    display: 'flex',
    alignItems: 'center',
  },
  vault_action_button_container_desktop: {
    display: 'none',
    [`@media screen and (min-width: 600px)`]: {
      display: 'block',
      flexShrink: 0,
      width: 200,
    },
  },
  vault_second_action_container: {
    padding: 16,
    backgroundColor: '#fff',
    borderRadius: 64,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 2,
  },
  vault_second_action_button: {
    borderRadius: 40,
    width: 188,
    height: 38,
    padding: '0 24px',
    cursor: 'pointer',
    transition: 'all .2s',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  vault_line_info_container: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
    height: 62,
    borderRadius: 62,
    padding: '0px 32px',
  },
  vault_instrument_logo_container: {
    display: 'none',
    [`@media screen and (min-width: 600px)`]: {
      width: 62,
      height: 62,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#fff',
      flexShrink: 0,
      borderRadius: '50%',
    },
  },
  vault_instrument_select: {
    width: '100%',
    '& .select__control::before': {
      content: "'INSTRUMENT'",
      paddingLeft: '8px',
      fontWeight: 700,
      color: '#16103A',
    },
    '& .select__control': {
      height: 62,
      border: 'none',
      borderRadius: 62,
      padding: '0 24px',
    },
    '& .select__single-value': {
      color: '#8E8DA0',
      fontWeight: 700,
      textAlign: 'right',
    },
    '& .select__indicator-separator': {
      display: 'none',
    },
  },
}
